# Generated by Django 5.1.5 on 2025-02-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=6, verbose_name='Shortened URL for customer')),
                ('long_url', models.TextField(verbose_name='Long URL provided by customer')),
            ],
            options={
                'db_table': 'urls',
            },
        ),
    ]
