# Generated by Django 5.1.5 on 2025-02-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.BigIntegerField(default=0, verbose_name='Incremental counter for generating base62 string')),
            ],
            options={
                'db_table': 'urlcounter',
            },
        ),
        migrations.RemoveField(
            model_name='urls',
            name='short_url',
        ),
        migrations.AddField(
            model_name='urls',
            name='short_code',
            field=models.CharField(default='', max_length=8, verbose_name='Shortened url code for customer'),
            preserve_default=False,
        ),
    ]
